name: "Repository set labels sync"
description: "Aggregates and syncs labels across a set of repositories."

on:
  workflow_dispatch:

inputs:
  labels-json-path:
    description: "Where to store labels for repositories"
    required: true
    default: "path/to/data"
  repositories-json-path:
    description: "Path to JSON file containing list of repository URLs."
    required: true
    default: "path/to/json"

runs:
  using: 'node12'
  main: 'write-labels/index.js'