name: "sync-labels"
on:
  workflow_dispatch:

jobs:
  # unit tests
  run:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     token: ${{ secrets.SYNC_LABELS_PAT }}
      #     fetch-depth: 0
      - uses: ./
        with:
          labels-json-path: "data/labels.json"
          repositories-json-path: "data/repositories.json"
          token: ${{ secrets.SYNC_LABELS_PAT }}
