name: "sync-labels"
on:
  workflow_dispatch:

jobs:
  # unit tests
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          data-directory: "_actions/data/"
          repositories-filename: "repositories.json"
          labels-filename: "labels.json"
          token: ${{ secrets.SYNC_LABELS_PAT }}
